import HomePage from "./HomePage";
import SignUpPage from "./SignUpPage";
import CoursePage from "./CoursePage";
import UserHomepage from "./UserHomepage";
import ProgressPage from "./ProgressPage";
import QuizPage from "./QuizPage";
import ExamReviewPage from "./ExamReviewPage";
import AssignmentPage from "./AssignmentPage";
import CoursesPage from "./CoursesPage";
export{HomePage, ExamReviewPage, SignUpPage, CoursePage, CoursesPage, AssignmentPage,UserHomepage, QuizPage,ProgressPage };